version: '2'
networks:
    ssnet:
       ipam:
         config:
         - subnet: 172.200.210.0/24
services:
  mesin1:
    container_name: mesin-1
    image: jupyter/scipy-notebook
    user: root
    ports:
      - "60001:8888"
      - "20001:20000"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./workmesin1:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    networks:
    - ssnet
  mesin2:
    container_name: mesin-2
    image: jupyter/scipy-notebook
    user: root
    ports:
      - "60002:8888"
      - "20002:20000"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./workmesin2:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    networks:
    - ssnet
  mesin3:
    container_name: mesin-3
    image: jupyter/scipy-notebook
    user: root
    ports:
      - "60003:8888"
      - "20003:20000"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./workmesin3:/home/jovyan/work
      - ./script:/script
    command: "sh /script/run.sh"
    networks:
    - ssnet
#  mesin4:
#    container_name: mesin-4
#    image: gopherdata/gophernotes:latest-ds
#    user: root
#    ports:
#      - "60004:8888"
#      - "20004:20000"
#    environment:
#      - "DOCKER_STACKS_JUPYTER_CMD=lab"
#      - "GRANT_SUDO=yes"
#    volumes:
#      - ./workmesin4:/home/jovyan/work
#      - ./script:/script
#    command: "sh /script/run-go.sh"
#    networks:
#    - ssnet

