version: '2'
networks:
    ssnet:
       ipam:
         config:
         - subnet: 172.200.210.0/24
services:
  mesin1:
    container_name: mesin-1
    build:
      context: ./jkernel
      dockerfile: Dockerfile
    user: root
    ports:
      - "60001:8888"
      - "20001:20000"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./workmesin1:/home/jovyan/work
      - ./script:/script
    entrypoint: "sh /script/run-go.sh"
    #command: "sh /script/run-go.sh"
    #entrypoint: "/bin/sh -c 'while true;do sleep 10000;done'"
    networks:
    - ssnet
  mesin2:
    container_name: mesin-2
    build:
      context: ./jkernel
      dockerfile: Dockerfile
    user: root
    ports:
      - "60002:8888"
      - "20002:20000"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./workmesin2:/home/jovyan/work
      - ./script:/script
    entrypoint: "sh /script/run-go.sh"
    networks:
    - ssnet
  mesin3:
    container_name: mesin-3
    build:
      context: ./jkernel
      dockerfile: Dockerfile
    user: root
    ports:
      - "60003:8888"
      - "20003:20000"
    environment:
      - "DOCKER_STACKS_JUPYTER_CMD=lab"
      - "GRANT_SUDO=yes"
    volumes:
      - ./workmesin3:/home/jovyan/work
      - ./script:/script
    entrypoint: "sh /script/run-go.sh"
    networks:
    - ssnet


